### ISSUE TITLE
Outdated Code causes crash on start with Doggy Talents

### ISSUE THREAD

**Issue by Rsslone** [CreativeMD/ItemPhysicLite#2]
Apparently there is some outdated code, its better explained in this tread by the Doggy Talents developer.
https://github.com/percivalalb/DoggyTalents/issues/159

**Comment by CreativeMD** [comment]
That's because ItemPhysicLite has the same modid as ItemPhysic. I highly recommend to use the Full version anyway. ItemPhysicLite can be used for vanilla servers etc. To be honest, I don't want to fix it because it would require some more work (hope you don't mind). If you really really need the Lite instead of the Full version let me know.

**Comment by Rsslone** [comment]
Well the only reason I wanted Lite was because it was client side only which sounds nice server performance wise and I only wanted the item physics part, not the floating items and lava burning physics ect.

I actually decided to just remove DoggyTalents in favor of the Lite version. So no worries.
